export default [
  {
    to: "/pomodoro",
    className: "pomodoro",
    title: "Pomodoro",
    icon: "🕒",
    info: "Dynamic Timer",
  },
  {
    to: "/markdown-editor",
    className: "markdown-editor",
    title: "Markdown Editor",
    icon: "💻",
    info: "Text Editor",
  },
  {
    to: "/highlight-tabs",
    className: "highlight-tabs",
    title: "Highlight Tabs",
    icon: "🎫",
    info: "Web Browser",
  },
  {
    to: "/paper-rock-scissors",
    className: "paper-rock-scissors",
    title: "Paper Rock Scissors",
    icon: "✂️",
    info: "Classic Game",
  },
  {
    to: "/moving-boxes-zelda",
    className: "moving-boxes-zelda",
    title: "Moving Boxes Zelda",
    icon: "⚔️",
    info: "Adventure Game",
  },
  {
    to: "/infinite-image-gallery",
    className: "infinite-image-gallery",
    title: "Infinite Image Gallery",
    icon: "🖼️",
    info: "Photo Viewer",
  },
  {
    to: "/trivia",
    className: "trivia",
    title: "Trivia",
    icon: "📖",
    info: "Quiz and Knowledge",
  },
  {
    to: "/authentication",
    className: "authentication",
    title: "Authentication",
    icon: "🔒",
    info: "Login Application",
  },
  {
    to: "/web-speech-timers",
    className: "web-speech-timers",
    title: "Web Speech Timers",
    icon: "💬",
    info: "Chat and messaging",
  },
  {
    to: "/calendar-picker",
    className: "calendar-picker",
    title: "Calendar Picker",
    icon: "🗓️",
    info: "Scheduling & Time",
  },
];
