export default [
  {
    to: "/pomodoro",
    className: "pomodoro",
    title: "Pomodoro",
    icon: "🕒",
    info: "Dynamic Timer",
  },
  {
    to: "/markdown-editor",
    className: "markdown-editor",
    title: "Markdown Editor",
    icon: "💻",
    info: "Text Editor",
  },
  {
    to: "/highlight-tabs",
    className: "highlight-tabs",
    title: "Highlight Tabs",
    icon: "🎫",
    info: "Web Browser",
  },
  {
    to: "/paper-rock-scissors",
    className: "paper-rock-scissors",
    title: "Paper Rock Scissors",
    icon: "✂️",
    info: "Classic Game",
  },
  {
    to: "/adventure-link",
    className: "adventure-link",
    title: "Adventure Link",
    icon: "⚔️",
    info: "Open World Game",
  },
  {
    to: "/infinite-image-gallery",
    className: "infinite-image-gallery",
    title: "Infinite Image Gallery",
    icon: "🖼️",
    info: "Photo Viewer",
  },
  {
    to: "/trivia",
    className: "trivia",
    title: "Trivia",
    icon: "📖",
    info: "Quiz and Knowledge",
  },
  {
    to: "/authentication",
    className: "authentication",
    title: "Authentication",
    icon: "🔒",
    info: "Login Application",
  },
  {
    to: "/web-speech-timers",
    className: "web-speech-timers",
    title: "Web Speech Timers",
    icon: "💬",
    info: "Chat and messaging",
  },
  {
    to: "/calendar-picker",
    className: "calendar-picker",
    title: "Calendar Picker",
    icon: "🗓️",
    info: "Scheduling & Time",
  },
  {
    to: "/animated-chat",
    className: "animated-chat",
    title: "Animated Chat",
    icon: "🤖",
    info: "interactive, social",
  },
  {
    to: "/multiform",
    className: "multiform",
    title: "MultiForm",
    icon: "📱",
    info: "forms and input",
  },
  {
    to: "/memory-game",
    className: "memory-game",
    title: "Memory Game",
    icon: "🃏",
    info: "Card game",
  },
  {
    to: "/drag-drop-match",
    className: "drag-drop-match",
    title: "Drag Drop Match",
    icon: "📦",
    info: "card game",
  },
  {
    to: "/browser",
    className: "browser",
    title: "Web Browser",
    icon: "🌐",
    info: "Web surfing",
  },
  {
    to: "/realtime-search",
    className: "realtime-search",
    title: "Real Time Search",
    icon: "🔍",
    info: "Search Engine",
  },
  {
    to: "/chart-weather",
    className: "chart-weather",
    title: "Chart Weather",
    icon: "☀️",
    info: "Scheduling & Time",
  },
  {
    to: "/cartoon-social",
    className: "cartoon-social",
    title: "Cartoon Social",
    icon: "✌️",
    info: "Contact & Messaging",
  },
];
